shared:
  image: node:18

jobs:
  job_using_template_apple:
    requires: [~pr, ~commit]
    template: sagar1312/sd-job-template-apple@latest
  job_using_template_pear:
    requires: [ ~pr, ~commit ]
    template: sagar1312/sd-job-template-pear@latest
  job_not_using_template:
    requires: [~pr, ~commit]
    steps:
      - hello: echo "hello"